[project]
name = "drivelm-rag"
version = "0.1.0"
description = ""
authors = [
    {name = "Rohit Upadhya",email = "rohitupadhya18@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "matplotlib (>=3.10.5,<4.0.0)",
    "openai (>=1.99.9,<2.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "transformers (>=4.55.2,<5.0.0)",
    "accelerate (>=1.10.0,<2.0.0)",
    "torch (>=2.8.0,<3.0.0)",
    "pillow (>=11.3.0,<12.0.0)",
    "faiss-cpu (>=1.12.0,<2.0.0)",
    "tqdm (>=4.67.1,<5.0.0)",
    "qwen-vl-utils (>=0.0.11,<0.0.12)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false
[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
ruff = "^0.12.8"
isort = "^6.0.1"
pytest = "^8.4.1"
